# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'hello_player', 'Card']

# %% ../00_core.ipynb 2
from fastcore.utils import *

# %% ../00_core.ipynb 4
def hello_player(to):
    "Say hello to a player"
    return f'Hello {to}! From 00_core.ipynb'

# %% ../00_core.ipynb 7
# ["♣️","🔶","❤️","♠️"]
suits = "♠ ♣ ♦ ♥".split()
ranks = [None] + [x for x in range(2,11)] + "J Q K A".split()

# %% ../00_core.ipynb 9
class Card():
    def __init__(self, rank, suit):
        self.rank = rank
        self.suit = suit
    def __repr__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    def __eq__(self, a): return self.rank == a.rank
    def __gt__(self, a): return self.rank > a.rank
    def __st__(self, a): return self.rank < a.rank
    
