# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['hello_player']

# %% ../00_core.ipynb 3
def hello_player(to):
    "Say hello to a player"
    return f'Hello {to}! From 00_core.ipynb'
